# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af639e40ab7e95b9f180cf00f69e8a1767d2443c86cd8f0e347b29cc724bff29ef44f7e56d3519d52478a77c6fac7456cb0d3f041a70dc9f367835676b620e28

test:
  secret_key_base: 5bd3a53ee4c755138e337804f8c41716fbd78922365352271f79ebcd33922f6cc38aab0d5107a6c802d80622f9081508d57565d51d9d3ae0a2373c890fe8ac77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
